import { useState } from "react";
import AppLayout from "@/components/AppLayout";
import { EnterpriseTable, ErrorState, LoadingState, MetricCard, PageHeader } from "@/components/training/SaaSPrimitives";
import { trainingService } from "@/services/trainingService";
import { useTrainingQuery } from "@/hooks/useTraining";

const sections = ["scenarios", "rubrics", "feature flags", "model routing", "organizations", "competitions", "prompt versions", "cost analytics", "transcript audit"];
export default function AdminCMS() {
  const { data, isLoading, error } = useTrainingQuery(() => trainingService.getAdminCMS(), []); const [section, setSection] = useState("scenarios");
  if (isLoading) return <AppLayout><LoadingState /></AppLayout>; if (error || !data) return <AppLayout><ErrorState /></AppLayout>;
  return <AppLayout><div className="space-y-6 max-w-[1500px]"><PageHeader eyebrow="Admin CMS" title="Simulation Operations CMS" description="Manage scenarios, rubrics, model routing, organizations, roles, competitions, cost analytics, and transcript audit trails." action={<button className="h-10 px-4 rounded-md bg-primary text-primary-foreground text-sm font-medium">Create / Publish</button>} />
    <div className="grid grid-cols-1 md:grid-cols-4 gap-4"><MetricCard label="Scenarios" value={data.scenarios.length} /><MetricCard label="Rubrics" value={data.rubrics.length} /><MetricCard label="Organizations" value={data.organizations.length} /><MetricCard label="Monthly AI Cost" value={`$${data.organizations.reduce((a, o) => a + o.monthlyAiCost, 0).toLocaleString()}`} tone="warning" /></div>
    <div className="grid grid-cols-1 xl:grid-cols-12 gap-5"><aside className="xl:col-span-3 xr-glass rounded-xl p-2">{sections.map((s) => <button key={s} onClick={() => setSection(s)} className={`w-full text-left rounded-md px-3 py-2 text-sm capitalize ${section === s ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground hover:bg-accent"}`}>{s}</button>)}</aside><main className="xl:col-span-9">{section === "scenarios" && <EnterpriseTable columns={["Title", "Drill", "Source", "Difficulty", "Status", "Version"]} rows={data.scenarios.map((s) => [s.title, s.drillType.replace("_", " "), s.source.replace("_", " "), s.difficulty, s.status, <span className="font-mono">v{s.version}</span>])} />}{section === "rubrics" && <EnterpriseTable columns={["Name", "Drill", "Categories", "Published"]} rows={data.rubrics.map((r) => [r.name, r.drillType.replace("_", " "), r.categories.length, r.published ? "yes" : "no"])} />}{section === "feature flags" && <EnterpriseTable columns={["Flag", "Enabled", "Description"]} rows={data.featureFlags.map((f) => [f.label, <span className={f.enabled ? "text-success" : "text-muted-foreground"}>{f.enabled ? "on" : "off"}</span>, f.description])} />}{section === "model routing" || section === "prompt versions" ? <EnterpriseTable columns={["Name", "Model", "Version", "Status", "Cost"]} rows={data.promptVersions.map((p) => [p.name, p.model, <span className="font-mono">v{p.version}</span>, p.status, `$${p.costPerSession}`])} /> : null}{section === "organizations" && <EnterpriseTable columns={["Organization", "Plan", "Seats", "Monthly Cost"]} rows={data.organizations.map((o) => [o.name, o.plan, o.seats, `$${o.monthlyAiCost}`])} />}{section === "cost analytics" && <EnterpriseTable columns={["Route", "Sessions", "Avg Cost", "Status"]} rows={data.promptVersions.map((p, i) => [p.name, 180 + i * 42, `$${p.costPerSession}`, p.status])} />}{section === "transcript audit" && <EnterpriseTable columns={["Session", "Speaker", "Timestamp", "Text"]} rows={data.audit.map((t) => [t.sessionId, t.speaker, t.timestamp, t.text])} />}{section === "competitions" && <EnterpriseTable columns={["Competition", "Cohort", "Learners", "Status"]} rows={data.cohorts.map((c) => [c.name, c.id, c.learnerCount, "active"])} />}</main></div>
  </div></AppLayout>;
}
